"""add_round_stats_json

Revision ID: 2d7c2cbc5e8c
Revises: 5d311b10e93f
Create Date: 2026-04-03 13:16:31.037443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7c2cbc5e8c'
down_revision: Union[str, None] = '5d311b10e93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('round_stats', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'round_stats')
    # ### end Alembic commands ###
