"""Add is_ghost to User model

Revision ID: 385e2d4c812f
Revises: 989b8fc78f9e
Create Date: 2026-04-06 18:58:02.473450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385e2d4c812f'
down_revision: Union[str, None] = '989b8fc78f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ИЗМЕНЕНО: Добавлен server_default, чтобы миграция прошла на существующих данных
    op.add_column('users', sa.Column('is_ghost', sa.Boolean(), nullable=False, server_default='false'))
    
    op.alter_column('users', 'discord_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'discord_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('users', 'is_ghost')
    # ### end Alembic commands ###
