"""rename_stat_fields

Revision ID: 50fe15e5035b
Revises: 6052acdff384
Create Date: 2026-04-03 12:47:18.497033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50fe15e5035b'
down_revision: Union[str, None] = '6052acdff384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_player_heroes', sa.Column('eliminations', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('final_blows', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('barrier_damage_dealt', sa.Float(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('hero_damage_dealt', sa.Float(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('healing_dealt', sa.Float(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('defensive_assists', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('offensive_assists', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('objective_kills', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('ultimates_earned', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('ultimates_used', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('multikill_best', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('multikills', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('solo_kills', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('environmental_kills', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('environmental_deaths', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('critical_hits', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('critical_hit_accuracy', sa.Float(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('scoped_accuracy', sa.Float(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('scoped_critical_hit_accuracy', sa.Float(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('scoped_critical_hit_kills', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('shots_fired', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('shots_hit', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('shots_missed', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('scoped_shots_fired', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('scoped_shots_hit', sa.Integer(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('weapon_accuracy', sa.Float(), nullable=True))
    op.drop_column('match_player_heroes', 'healing_done')
    op.drop_column('match_player_heroes', 'obj_kills')
    op.drop_column('match_player_heroes', 'damage_dealt')
    op.drop_column('match_player_heroes', 'kills')
    op.drop_column('match_player_heroes', 'assists')
    op.add_column('match_players', sa.Column('eliminations', sa.Integer(), nullable=True))
    op.add_column('match_players', sa.Column('final_blows', sa.Integer(), nullable=True))
    op.add_column('match_players', sa.Column('hero_damage_dealt', sa.Float(), nullable=True))
    op.add_column('match_players', sa.Column('healing_dealt', sa.Float(), nullable=True))
    op.add_column('match_players', sa.Column('defensive_assists', sa.Integer(), nullable=True))
    op.add_column('match_players', sa.Column('offensive_assists', sa.Integer(), nullable=True))
    op.add_column('match_players', sa.Column('objective_kills', sa.Integer(), nullable=True))
    op.add_column('match_players', sa.Column('ultimates_earned', sa.Integer(), nullable=True))
    op.add_column('match_players', sa.Column('ultimates_used', sa.Integer(), nullable=True))
    op.drop_column('match_players', 'healing_done')
    op.drop_column('match_players', 'obj_kills')
    op.drop_column('match_players', 'damage_dealt')
    op.drop_column('match_players', 'kills')
    op.drop_column('match_players', 'assists')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_players', sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match_players', sa.Column('kills', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match_players', sa.Column('damage_dealt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('match_players', sa.Column('obj_kills', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match_players', sa.Column('healing_done', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('match_players', 'ultimates_used')
    op.drop_column('match_players', 'ultimates_earned')
    op.drop_column('match_players', 'objective_kills')
    op.drop_column('match_players', 'offensive_assists')
    op.drop_column('match_players', 'defensive_assists')
    op.drop_column('match_players', 'healing_dealt')
    op.drop_column('match_players', 'hero_damage_dealt')
    op.drop_column('match_players', 'final_blows')
    op.drop_column('match_players', 'eliminations')
    op.add_column('match_player_heroes', sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match_player_heroes', sa.Column('kills', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match_player_heroes', sa.Column('damage_dealt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('match_player_heroes', sa.Column('obj_kills', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match_player_heroes', sa.Column('healing_done', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('match_player_heroes', 'weapon_accuracy')
    op.drop_column('match_player_heroes', 'scoped_shots_hit')
    op.drop_column('match_player_heroes', 'scoped_shots_fired')
    op.drop_column('match_player_heroes', 'shots_missed')
    op.drop_column('match_player_heroes', 'shots_hit')
    op.drop_column('match_player_heroes', 'shots_fired')
    op.drop_column('match_player_heroes', 'scoped_critical_hit_kills')
    op.drop_column('match_player_heroes', 'scoped_critical_hit_accuracy')
    op.drop_column('match_player_heroes', 'scoped_accuracy')
    op.drop_column('match_player_heroes', 'critical_hit_accuracy')
    op.drop_column('match_player_heroes', 'critical_hits')
    op.drop_column('match_player_heroes', 'environmental_deaths')
    op.drop_column('match_player_heroes', 'environmental_kills')
    op.drop_column('match_player_heroes', 'solo_kills')
    op.drop_column('match_player_heroes', 'multikills')
    op.drop_column('match_player_heroes', 'multikill_best')
    op.drop_column('match_player_heroes', 'ultimates_used')
    op.drop_column('match_player_heroes', 'ultimates_earned')
    op.drop_column('match_player_heroes', 'objective_kills')
    op.drop_column('match_player_heroes', 'offensive_assists')
    op.drop_column('match_player_heroes', 'defensive_assists')
    op.drop_column('match_player_heroes', 'healing_dealt')
    op.drop_column('match_player_heroes', 'hero_damage_dealt')
    op.drop_column('match_player_heroes', 'barrier_damage_dealt')
    op.drop_column('match_player_heroes', 'final_blows')
    op.drop_column('match_player_heroes', 'eliminations')
    # ### end Alembic commands ###
