"""add_new_stat_fields

Revision ID: 6052acdff384
Revises: 9cc4ed64323c
Create Date: 2026-04-03 12:20:20.824247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6052acdff384'
down_revision: Union[str, None] = '9cc4ed64323c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_player_heroes', sa.Column('healing_received', sa.Float(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('self_healing', sa.Float(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('all_damage_dealt', sa.Float(), nullable=True))
    op.add_column('match_player_heroes', sa.Column('obj_kills', sa.Integer(), nullable=True))
    op.add_column('match_players', sa.Column('healing_received', sa.Float(), nullable=True))
    op.add_column('match_players', sa.Column('self_healing', sa.Float(), nullable=True))
    op.add_column('match_players', sa.Column('all_damage_dealt', sa.Float(), nullable=True))
    op.add_column('match_players', sa.Column('obj_kills', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_players', 'obj_kills')
    op.drop_column('match_players', 'all_damage_dealt')
    op.drop_column('match_players', 'self_healing')
    op.drop_column('match_players', 'healing_received')
    op.drop_column('match_player_heroes', 'obj_kills')
    op.drop_column('match_player_heroes', 'all_damage_dealt')
    op.drop_column('match_player_heroes', 'self_healing')
    op.drop_column('match_player_heroes', 'healing_received')
    # ### end Alembic commands ###
