"""add draft models

Revision ID: 989b8fc78f9e
Revises: f6d38f95db1e
Create Date: 2026-04-06 09:33:43.004424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '989b8fc78f9e'
down_revision: Union[str, None] = 'f6d38f95db1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_captains', sa.Column('captain_role', sa.String(), nullable=True))
    op.drop_constraint('draft_captains_draft_session_id_fkey', 'draft_captains', type_='foreignkey')
    op.drop_constraint('draft_captains_user_id_fkey', 'draft_captains', type_='foreignkey')
    op.create_foreign_key(None, 'draft_captains', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'draft_captains', 'draft_sessions', ['draft_session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('draft_picks', 'is_auto_pick',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint('draft_picks_draft_session_id_fkey', 'draft_picks', type_='foreignkey')
    op.drop_constraint('draft_picks_captain_id_fkey', 'draft_picks', type_='foreignkey')
    op.drop_constraint('draft_picks_picked_user_id_fkey', 'draft_picks', type_='foreignkey')
    op.create_foreign_key(None, 'draft_picks', 'draft_captains', ['captain_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'draft_picks', 'users', ['picked_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'draft_picks', 'draft_sessions', ['draft_session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('draft_sessions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('draft_sessions', 'pick_time_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('draft_sessions', 'team_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('draft_sessions', 'current_pick_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('draft_sessions', 'role_slots',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_constraint('draft_sessions_tournament_id_fkey', 'draft_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'draft_sessions', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tournament_participants', 'checkedin_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tournaments', 'registration_open',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tournaments', 'registration_close',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tournaments', 'checkin_open',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tournaments', 'checkin_close',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tournaments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('tournaments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournaments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('tournaments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('tournaments', 'checkin_close',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tournaments', 'checkin_open',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tournaments', 'registration_close',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tournaments', 'registration_open',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tournament_participants', 'checkedin_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'draft_sessions', type_='foreignkey')
    op.create_foreign_key('draft_sessions_tournament_id_fkey', 'draft_sessions', 'tournaments', ['tournament_id'], ['id'])
    op.alter_column('draft_sessions', 'role_slots',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('draft_sessions', 'current_pick_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('draft_sessions', 'team_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('draft_sessions', 'pick_time_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('draft_sessions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'draft_picks', type_='foreignkey')
    op.drop_constraint(None, 'draft_picks', type_='foreignkey')
    op.drop_constraint(None, 'draft_picks', type_='foreignkey')
    op.create_foreign_key('draft_picks_picked_user_id_fkey', 'draft_picks', 'users', ['picked_user_id'], ['id'])
    op.create_foreign_key('draft_picks_captain_id_fkey', 'draft_picks', 'draft_captains', ['captain_id'], ['id'])
    op.create_foreign_key('draft_picks_draft_session_id_fkey', 'draft_picks', 'draft_sessions', ['draft_session_id'], ['id'])
    op.alter_column('draft_picks', 'is_auto_pick',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'draft_captains', type_='foreignkey')
    op.drop_constraint(None, 'draft_captains', type_='foreignkey')
    op.create_foreign_key('draft_captains_user_id_fkey', 'draft_captains', 'users', ['user_id'], ['id'])
    op.create_foreign_key('draft_captains_draft_session_id_fkey', 'draft_captains', 'draft_sessions', ['draft_session_id'], ['id'])
    op.drop_column('draft_captains', 'captain_role')
    # ### end Alembic commands ###
