"""add_player_profile_fields

Revision ID: 9cc4ed64323c
Revises: 005matches
Create Date: 2026-04-02 12:49:33.714231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc4ed64323c'
down_revision: Union[str, None] = '005matches'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_participants', sa.Column('is_allowed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('primary_role', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('secondary_role', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'secondary_role')
    op.drop_column('users', 'primary_role')
    op.drop_column('users', 'display_name')
    op.drop_column('tournament_participants', 'is_allowed')
    # ### end Alembic commands ###
