"""add_google_sheet_id_to_tournaments

Revision ID: b7d9e517864f
Revises: 014_add_next_encounter_id
Create Date: 2026-04-15 18:41:39.330767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d9e517864f'
down_revision: Union[str, None] = '014_add_next_encounter_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_encounters_stage_id'), 'encounters', ['stage_id'], unique=False)
    op.create_foreign_key(None, 'encounters', 'tournament_stages', ['stage_id'], ['id'], ondelete='SET NULL')
    op.alter_column('tournament_participants', 'is_captain',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_tournament_participants_group_id'), 'tournament_participants', ['group_id'], unique=False)
    op.create_foreign_key(None, 'tournament_participants', 'stage_groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament_participants', type_='foreignkey')
    op.drop_index(op.f('ix_tournament_participants_group_id'), table_name='tournament_participants')
    op.alter_column('tournament_participants', 'is_captain',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_constraint(None, 'encounters', type_='foreignkey')
    op.drop_index(op.f('ix_encounters_stage_id'), table_name='encounters')
    # ### end Alembic commands ###
